name: Generate hosts.txt from sources.json

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '.dev/**'
      - './.github/**'
      - '.gitignore'
      - 'README.md'
  schedule:
     - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout code
        if: ${{ success() }}
        uses: actions/checkout@v5

      - name: Lint JSON files
        if: ${{ success() }}
        uses: ocular-d/json-linter@0.0.2

      - name: Set variables
        if: ${{ success() }}
        run: |
          TAG=$(cat "${GITHUB_WORKSPACE}/VERSION")
          echo "TAG=${TAG}" >> ${GITHUB_ENV}
          echo "FILE_NAME=hosts.txt" >> ${GITHUB_ENV}
          echo "FILE_NAME_MIN=hosts.min.txt" >> ${GITHUB_ENV}
          echo "FILE_NAME_FULL=${GITHUB_WORKSPACE}/hosts.txt" >> ${GITHUB_ENV}
          echo "FILE_NAME_FULL_MIN=${GITHUB_WORKSPACE}/hosts.min.txt" >> ${GITHUB_ENV}

      - name: (DEBUG) Check variables
        if: ${{ success() }}
        run: |
          echo "TAG=${TAG}"
          echo "FILE_NAME_FULL=${FILE_NAME_FULL}"

      - name: (DEBUG) Verify if required dependencies are installed
        if: ${{ success() }}
        run: |
          curl --version | head -1
          openssl version | head -1
          unzip -v | head -1
          python --version | head -1
          pip --version | head -1
          jq --version | head -1

          curl -sfL "https://github.com/ScriptTiger/Hosts-BL/releases/download/11SEP2024/hosts-bl_linux_amd64.zip" -o "${GITHUB_WORKSPACE}/hosts-bl.zip"
          unzip -qq "${GITHUB_WORKSPACE}/hosts-bl.zip" "hosts-bl" -d "${GITHUB_WORKSPACE}"
          chmod +x "${GITHUB_WORKSPACE}/hosts-bl"

          python -m pip install --break-system-packages --quiet adblock-decoder

      - name: (HELPER) Remove old files
        if: ${{ success() }}
        run: |
          rm -f "${FILE_NAME_FULL}"
          rm -f "${FILE_NAME_FULL_MIN}"

      - name: Generate hosts file from sources
        if: ${{ success() }}
        run: |
          mapfile -t urls < <(cat "${GITHUB_WORKSPACE}/sources.json" | jq -r '.[] | .sources[].url')
          for i in "${!urls[@]}"; do curl -sfL "${urls[$i]}" >> "${FILE_NAME_FULL}.raw"; done

      - name: (DEBUG) Check file size
        if: ${{ success() }}
        run: echo "$(stat -c%s "${FILE_NAME_FULL}.raw" | numfmt --to=iec)"

      - name: Decode hosts file
        if: ${{ success() }}
        run: adblock2hosts --ip 0.0.0.0 -o "${FILE_NAME_FULL}.decoded" "${FILE_NAME_FULL}.raw"

      - name: Clean hosts file
        if: ${{ success() }}
        run: |
          grep -vF -e "0.0.0.0 _" -e "0.0.0.0 -" -e "0.0.0.0 ." -e "&" -e "|" -e ":" -e "^" -e "?" -e "%" "${FILE_NAME_FULL}.decoded" > "${FILE_NAME_FULL}.clean"
          grep -vFxf "${GITHUB_WORKSPACE}/lists/allow-list.txt" "${FILE_NAME_FULL}.clean" > "${FILE_NAME_FULL}.allowlisted"
          cat "${GITHUB_WORKSPACE}/lists/block-list.txt" >> "${FILE_NAME_FULL}.allowlisted"
          sort -u "${FILE_NAME_FULL}.allowlisted" > "${FILE_NAME_FULL}"

      - name: (DEBUG) Check file size
        if: ${{ success() }}
        run: echo "$(stat -c%s "${FILE_NAME_FULL}" | numfmt --to=iec)"

      - name: Minimize hosts file
        if: ${{ success() }}
        run: ./hosts-bl -f "hosts" -i "${FILE_NAME_FULL}" -compression "9" -hash "256" -from_blackhole "0.0.0.0" -to_blackhole "0.0.0.0" -o "${FILE_NAME_FULL_MIN}" < /dev/null

      - name: (DEBUG) Check file size
        if: ${{ success() }}
        run: echo "$(stat -c%s "${FILE_NAME_FULL_MIN}" | numfmt --to=iec)"

      - name: (HELPER) Remove temp files
        if: ${{ success() }}
        run: |
          rm -f "${FILE_NAME_FULL}.raw"
          rm -f "${FILE_NAME_FULL}.decoded"
          rm -f "${FILE_NAME_FULL}.clean"
          rm -f "${FILE_NAME_FULL}.allowlisted"
          rm -f "${GITHUB_WORKSPACE}/hosts-bl"
          rm -f "${GITHUB_WORKSPACE}/hosts-bl.zip"

      - name: Commit new hosts file
        if: ${{ success() }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config user.name "repo-bot"
          git config user.email "repo-bot"
          git remote set-url origin "https://${{ github.repository_owner }}:${BOT_TOKEN}@github.com/${{ github.repository }}.git"
          git add "${FILE_NAME}" ${FILE_NAME_MIN}
          git commit -m "${FILE_NAME} and ${FILE_NAME_MIN} autogenerated, ${TAG}"
          git tag | grep "${TAG}" && git tag -d "${TAG}"
          git tag -a "${TAG}" -m "${TAG}"
          git push -u origin main
          git push --tags